name: FirebaseDistributionApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "13.0"
targets:
  FirebaseDistributionApp:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - FirebaseDistributionApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.firebasedistributionapp
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        INFOPLIST_FILE: FirebaseDistributionApp/Info.plist
