name: RequestifyDemo
options:
  deploymentTarget:
    iOS: 13.0
  bundleIdPrefix: com.example
  createIntermediateGroups: true
packages:
  Requestify:
    path: ..

targets:
  RequestifyDemo:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    sources:
      - RequestifyDemo
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.requestifydemo
      DEVELOPMENT_TEAM: YOUR_TEAM_ID
      INFOPLIST_FILE: RequestifyDemo/Info.plist
      TARGETED_DEVICE_FAMILY: 1
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - product: Requestify
        package: Requestify
  RequestifyDemoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RequestifyDemoTests
        optional: true
    dependencies:
      - target: RequestifyDemo
schemes:
  RequestifyDemo:
    build:
      targets:
        RequestifyDemo: all
    test:
      gatherCoverageData: true
      targets:
        - name: RequestifyDemoTests
          parallelizable: true
          randomExecutionOrder: true
    run:
      config: Debug
    archive:
      config: Release
