name: RequestifyApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 13.0
  createIntermediateGroups: true
  
packages:
  Requestify:
    path: ..

targets:
  RequestifyApp:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    sources:
      - RequestifyApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.requestifyapp
        INFOPLIST_FILE: RequestifyApp/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: Requestify
        product: Requestify

schemes:
  RequestifyApp:
    build:
      targets:
        RequestifyApp: all
    run:
      config: Debug
    archive:
      config: Release
